- name: "Play 1 - Create directory"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Create directory to store output files"
      file:
        path: ./snmp_write
        state: directory

- name: "Play 2 - configure snmp and acl"
  hosts: all
  gather_facts: false
  tasks:
    - name: "configure acls"
      ios_config:
        lines:
          - permit host 10.242.3.68
          - permit host 10.242.3.69
          - permit host 10.242.3.55
          - permit host 10.170.3.35
        parents: ip access-list standard 9
        match: exact

    - name: "configure snmp community"
      ios_config:
        lines:
          - snmp-server community Cf9m9m7 RO 9

    - name: "save running to startup when modified"
      ios_config:
        save_when: modified

    - name: "check acl"
      ios_command:
        commands:
          - "sh run | in access-list 9|snmp-server community"

      register: output


    - name: "create output file"
      copy:
        content: "{{ output }}"
        dest: "./snmp_write/{{ inventory_hostname }}.json"

